### ISSUE TITLE
Doesn't work at all with angular 1.2.26

### ISSUE THREAD

**Issue by chinchang** [Linkurious/angular-performance#13]
No error in console. All metrics show zero.

**Comment by callicles** [comment]
I have never tested with 1.2.26.

Have you tried refreshing the page once the Angular tab is open ? `Ctrl-Maj-R`

**Comment by chinchang** [comment]
Yes, I did try that. No difference. Everything remains 0. Anyways, I am trying it with 1.2.28 now which I am planning to upgrade to. Will update here if I face issue with that too.

**Comment by callicles** [comment]
All right. Please create another issue for 1.2.28 if you stumble upon one. 

Thanks for your feedback.
