### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by sharp-bits** [Linkurious/angular-performance#18]
Extension is broken on Chrome OSX Version 44.0.2403.130 (64-bit). The background.html shows:

Unchecked runtime.lastError while running tabs.executeScript: Cannot access contents of url "chrome-devtools://devtools/bundled/devtools.html?&remoteBase=https://chrome-devtools-frontend.appspot.com/serve_file/@199588/&dockSide=undocked&toolbarColor=rgba(230,230,230,1)&textColor=rgba(0,0,0,1)". Extension manifest must request permission to access this host.
    at devToolsListener (chrome-extension://hejbpbhdhhchmmcgmccpnngfedalkmkm/src/background.js:34:21)

**Comment by callicles** [comment]
Thanks for reporting,

Does this appear when you simply inspect a normal web tab ? Or is it when you inspect the devtools with the devtools ?

**Comment by hokkaido** [comment]
When I first installed it, there was an Angular tab with angular-performance in devtools. But now it's gone and the aforementioned error appears when clicking "Inspect views: background page" in angular-performance's section in chrome://extensions.
