### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by goldylucks** [Linkurious/angular-performance#19]
I get this when loading chrome, and the extension reports 0's on all three values

inspector.js:83
_angularInjector = angular.element(document.querySelector('[ng-app],[data-ng-app]')).injector().get;

if I change it to this:
_angularInjector = angular.element(document).injector().get;

It works

I'm bootstraping angular:
function onReady() {
    angular.bootstrap(document, ['blockchess']);
}

if (Meteor.isCordova)
    angular.element(document).on("deviceready", onReady);
else
    angular.element(document).ready(onReady);

we can cover both cases like this:
_angularInjector = (angular.element(document.querySelector('[ng-app],[data-ng-app]')).injector() || angular.element(document).injector()).get;

Or a bit cleaner like so:
var injector = angular.element(document.querySelector('[ng-app],[data-ng-app]')).injector() || angular.element(document).injector()
_angularInjector = (injector).get;

Let me know if this make sense, I'll create a pull request

and please hurry this extension seems cool I wanna use it! :)

**Comment by callicles** [comment]
Noted, will try to get on this tomorrow.

**Comment by callicles** [comment]
Could you try the version on develop, plz ? Just pushed a couple of things

To use the dev version here are the instructions:
- Remove the extension version installed from the chrome store
- Clone the repository
- Switch to the develop git branch (Latest version)
- run `npm install`
- run `npm build`
- Go into the Chrome main menu -> more tools -> extension
- Enable developer mode
- Load unpacked extension
- select the extension folder of this repository
